#!/usr/bin/env ruby
# frozen_string_literal: true

Signal.trap('INT') { exit 2 }

require_relative '../lib/cipher_me_up'

begin
  CipherMeUp::MainCommand.start(ARGV)
rescue StandardError => e
  puts e.message
  exit 1
end
